### ISSUE TITLE
Error trying to open Power Mode options

### ISSUE THREAD

**Issue by sloopernine** [LiamMorrow/Visual-Studio-Power-Mode#13]
Trying to open options of the extension ( tools/options/power mode ), only get the text "An error occurred loading this property page" and nothing else.

**Comment by parnic** [comment]
Which version of Visual Studio?

**Comment by abdulahadnbs** [comment]
Same issue. In VS2013, extension is installed but its not opening and not working.

**Comment by parnic** [comment]
@abdulahadnbs - reported and fixed as issue #15

**Comment by abdulahadnbs** [comment]
Its not fixed. its not working still.

**Comment by parnic** [comment]
@abdulahadnbs - if you're installing the extension from the Visual Studio gallery (as opposed to building it yourself), then you'll still be busted. You will have to wait for v1.1.5 to be posted. Or build it yourself from source.

**Comment by abdulahadnbs** [comment]
I downloaded the project but its not loading in VS2013

**Comment by parnic** [comment]
@abdulahadnbs - right, the project must be built in VS2015. The extension, once built, is supposed to work in 2012-2013.

Now if we could allow the original reporter to detail _his_ issue, that would be great. :)

**Comment by parnic** [comment]
Probably fixed in v1.1.5.

**Comment by sloopernine** [comment]
@parnic Sorry been working all day, I get same issues as @abdulahadnbs

Cant build from source as it requires VS2015, and installing the extension dont work. Think I got some message first time, clicked ok by reflex and didnt read in detail. But something about the extension could not be loaded as there was another extension interfering. It didnt mention what other extension. The only one I can think of that are not included from beginning in VS are Visual Studio Assist X
