### ISSUE TITLE
Add toggle on/off by keyboard shortcut

### ISSUE THREAD

**Issue by ThomasZitzler** [LiamMorrow/Visual-Studio-Power-Mode#18]
Could you please add toggle on/off functionality? Best would be to have a keyboard shortcut for that.

Currently it's only possible to enable/disable the extension and that requires a Visual Studio restart.

**Comment by jeroldhaas** [comment]
:+1: this feature. If not include a binding, at least provide the ability to create a binding.

**Comment by nbarbettini** [comment]
> provide the ability to create a binding.

:+1: on this.

**Comment by LiamMorrow** [comment]
I'll have a look after work today

**Comment by jeroldhaas** [comment]
I've stubbed in some of the code on my fork. It was coded in VS Code, without any VS Extensibility API -- I just need Guids and CommandIds, I believe, so it's as of yet not complete enough for a PR.
https://github.com/jeroldhaas/Visual-Studio-Power-Mode

**Comment by Liz4v** [comment]
+1

**Comment by magicnanners** [comment]
Any update on this?

**Comment by jeroldhaas** [comment]
I'm stalled at the moment. If someone wants to pick up where I've left off, they're welcome to it. 😄

**Comment by LiamMorrow** [comment]
#40 should fix this
