### ISSUE TITLE
Keystroke sound effects 

### ISSUE THREAD

**Issue by sloopernine** [LiamMorrow/Visual-Studio-Power-Mode#21]
I would like to be able to add sound effects of different keys, for example able to add one sound when ctrl-copy another for paste another when pressing space, enter.  Also perhaps array of 5 different when typing letters and numbers to add some randomness to it. This would allow me to add typewriter sounds or others if I want to change. Should be possible to switch on/off aswell.

**Comment by willysunny** [comment]
That sounds more like a suggestion than issue. Issues are bugs, those are not.

**Comment by LiamMorrow** [comment]
Hmm I'm not too sold on the idea of sound in it.  I'll tentatively close this but if a pull request comes in that implements it I'll consider adding it
