### ISSUE TITLE
A bad way to get the color of keyword

### ISSUE THREAD

**Issue by RightFS** [LiamMorrow/Visual-Studio-Power-Mode#28]
after got the front-size and the postion of cursor.can you capture the screen pixels and detect its color?

**Comment by LiamMorrow** [comment]
it might be possible, but unfortunately I don't have the time to work on this very often anymore

**Comment by LiamMorrow** [comment]
Gonna go ahead and close this one.  Doesn't seem feasible without nuking the CPU
