### ISSUE TITLE
Doesn't support any product

### ISSUE THREAD

**Issue by maggot99999** [LiamMorrow/Visual-Studio-Power-Mode#29]
09/03/16 16:13:05 - Microsoft VSIX Installer
09/03/16 16:13:05 - -------------------------------------------
09/03/16 16:13:05 - Initializing Install...
09/03/16 16:13:05 - Extension Details...
09/03/16 16:13:05 -     Identifier      : PowerMode.Liam Morrow.53e86655-8a9a-4544-ac12-4aef42035b5f
09/03/16 16:13:05 -     Name            : PowerMode
09/03/16 16:13:05 -     Author          : Liam Morrow
09/03/16 16:13:05 -     Version         : 1.1.5
09/03/16 16:13:05 -     Description     : An extension that attempts to clone the power mode in Atom found here : https://atom.io/packages/activate-power-mode
09/03/16 16:13:05 -     Locale          : en-US
09/03/16 16:13:05 -     MoreInfoURL     : 
09/03/16 16:13:05 -     InstalledByMSI  : False
09/03/16 16:13:05 -     SupportedFrameworkVersionRange : [4.5,)
09/03/16 16:13:05 - 
09/03/16 16:13:05 -     Supported Products : 
09/03/16 16:13:05 -         Microsoft.VisualStudio.IntegratedShell
09/03/16 16:13:05 -             Version : [11.0,14.0]
09/03/16 16:13:05 - 
09/03/16 16:13:05 -     References      : 
09/03/16 16:13:05 -         -------------------------------------------------------
09/03/16 16:13:05 -         Identifier   : Microsoft.VisualStudio.MPF
09/03/16 16:13:05 -         Name         : Visual Studio MPF
09/03/16 16:13:05 -         Version      : [11.0,13.0)
09/03/16 16:13:05 -         MoreInfoURL  : 
09/03/16 16:13:05 -         Nested       : No
09/03/16 16:13:05 - 
09/03/16 16:13:05 - 
09/03/16 16:13:05 - Searching for applicable products...
09/03/16 16:13:06 - Found installed product - Microsoft Visual Studio Express 2015 for Windows Desktop
09/03/16 16:13:06 - Found installed product - Global Location
09/03/16 16:13:06 - Found installed product - AtmelStudio
09/03/16 16:13:06 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by LiamMorrow** [comment]
Interesting.  I'm unable to reproduce this unfortunately.

**Comment by maggot99999** [comment]
Hi, it seems it was VS Express 2015 version which did not support extensions for some reason. So I switched to Community 2016 and everything starts to work. Thank you for your attention anyway :) Appreciate it!

**Comment by silasary** [comment]
Yeah, Express explicitly didn't support extensions of any kind.   It was part of the restrictions they put on it as part of being a free release.

Dropping this (and a couple other silly restrictions) was a significant factor in why they renamed the free offering to Community for later releases.
