### ISSUE TITLE
Please provide earlier versions

### ISSUE THREAD

**Issue by Radzhab** [LiamMorrow/Visual-Studio-Power-Mode#3]
vs2012,2013

**Comment by sloopernine** [comment]
Agree, please make it work with visual studio 2013 if possible

**Comment by LiamMorrow** [comment]
It's something I can look into.  This was just a quick thing I whipped together, my first time making a Visual studio extension and I believe they changed the framework for 2015.

**Comment by sloopernine** [comment]
I hope you find the time and energy to make it work with earlier version. Sure I could upgrade to the free community version of VS. But then I would not be able to use my other extensions :/

**Comment by lyubaskubchenko** [comment]
Agree, please make it work with visual studio 2013 if possible

**Comment by LiamMorrow** [comment]
Thanks to @parnic for getting this done for me, I'm on holidays right now so finding time is a bit tricky
