### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by vitaliibudnyi** [LiamMorrow/Visual-Studio-Power-Mode#5]
Installer log:
[VSIXInstaller_b9fec8c2-a926-41b4-a2b7-d3f03b2be8db.log.txt](https://github.com/LiamMorrow/Visual-Studio-Power-Mode/files/53049/VSIXInstaller_b9fec8c2-a926-41b4-a2b7-d3f03b2be8db.log.txt)

**Comment by Mochimazui** [comment]
http://stackoverflow.com/questions/18848925/visual-studio-2013-new-project-unspecified-error-exception-from-hresult-0x

Try whether these solution works for you. O.O

**Comment by LiamMorrow** [comment]
I've updated the source with @parnic 's changes so try that.

**Comment by sloopernine** [comment]
Well, the project cant be opened with VS2013 at least, says the project are created with newer version. So I think I have to wait until you have updated "Link to built Extension".

**Comment by parnic** [comment]
@sloopernine - yep, exactly. The version will need to be revved and a new upload posted to the extension gallery.

**Comment by sloopernine** [comment]
Would be awesome if someone could build new extension install

**Comment by vitaliibudnyi** [comment]
I thought I can download and install it manually. It only installs through Visual  Studio "Extensions and updates..." manager. But I guess this issue may be closed.
